chore: add requirements.txt and review DEV_NOTES.md
questdb/py-questdb-client pull request #1
Opened 2022-07-14 14:29 UTC by marregui

2022-07-14 14:42 UTC, amunra commented
We probably don't want `examples/__init__.py` as examples is just a directory and not a package.

2022-07-14 14:46 UTC, amunra requested changes

2022-07-14 14:46 UTC, amunra commented on requirements.txt
> +tox>=3.25.1
I'm not sure this is correct:

If I understand correctly requirements is for runtime, whilst we only really care about having these tools (incidentally, tox is no longer required) at build time.

Probably worth explanding:

```
[project.optional-dependencies]
publish = ["twine", "wheel"]
ci = ["cibuildwheel"]
```

and

```
[build-system]
requires = [
    # Setuptools 18.0 and above properly handles Cython extensions.
    "setuptools>=45.2.0",
    "wheel>=0.34.2",
    "cython>=0.29.24"]
```

In `pyproject.toml`.

2022-07-14 14:46 UTC, amunra commented on proj.py
> +    escaped_cmd = ' '.join(shlex.quote(str(arg)) for arg in args)
Nice catch.

2022-07-14 14:46 UTC, amunra commented on README.rst
>  Installation
Leave this in, for now.

2022-07-14 14:46 UTC, amunra commented on DEV_NOTES.rst
> -=================
Why are you deleting the file?

2022-07-14 14:46 UTC, amunra commented on examples/line_sender.py
> +    with Sender(host='localhost', port=9009) as sender:
This example, and more like this, including authentication and TLS, shoud be exposed to the docs.

2022-07-14 14:46 UTC, amunra commented on examples/line_sender.py
> +                    'name_e': 'val_b'
Probably a separate example with also `at=` and a `datetime.datetime` timestamp.

2022-07-15 11:11 UTC, marregui commented
will open a new PR, this one serve the purpose of discussing the project etc.

2022-07-15 11:11 UTC, closed without merging